import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  variable: '--robo-font',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Ignite Coll',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased  bg-gray-900 text-gray-100`}
      >
        {children}
      </body>
    </html>
  );
}
